image: clojure:alpine

stages:
  - test

test:
  stage: test
  services:
    - postgres:9.6
  variables:
    - DB_URL: postgresql://test:test@postgres/xchange
    - POSTGRES_DB: xchange
    - POSTGRES_USER: test
    - POSTGRES_PASSWORD: test
  script:
    - lein test
  tags:
    - docker
